import { Metadata } from 'next';
import { defaultMetadata, buildSoftwareApplicationJsonLd, buildVideoObjectJsonLd } from '@/lib/seo';
import { LandingHero } from '@/components/LandingHero';
import { GeneratorPanel } from '@/components/GeneratorPanel';

export const metadata: Metadata = defaultMetadata;

export default function Home() {
  const softwareSchema = buildSoftwareApplicationJsonLd();
  const videoSchema = buildVideoObjectJsonLd({
    name: "Sample AI Generated Short",
    description: "An example of a faceless YouTube short generated by Emergent Shorts AI.",
    thumbnailUrl: "https://emergentshorts.ai/sample-thumb.jpg",
    uploadDate: "2026-04-26T08:00:00Z",
    duration: "PT30S",
    contentUrl: "https://emergentshorts.ai/sample.mp4"
  });

  return (
    <main className="min-h-screen bg-slate-950 text-slate-100 overflow-x-hidden selection:bg-blue-500/30 relative">
      {/* Dynamic Background Effects */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-blue-600/10 blur-[120px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full bg-purple-600/10 blur-[120px]" />
      </div>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(videoSchema) }}
      />

      {/* Navigation */}
      <nav className="w-full border-b border-slate-900/50 bg-slate-950/50 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 sm:px-8 h-20 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center font-bold text-white shadow-lg shadow-blue-900/20">
              E
            </div>
            <span className="font-bold text-xl tracking-tight text-white">Emergent Shorts</span>
          </div>
          <div className="hidden md:flex items-center gap-8">
            <button className="text-sm font-semibold text-slate-400 hover:text-white transition-colors">Pricing</button>
            <button className="text-sm font-semibold text-slate-400 hover:text-white transition-colors">Use Cases</button>
            <button className="bg-slate-900 hover:bg-slate-800 text-white text-sm font-bold py-2.5 px-5 rounded-xl border border-slate-800 transition-all active:scale-95">
              Launch App
            </button>
          </div>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-6 sm:px-8 pt-16 pb-24 relative z-10">
        {/* Top fold: Split layout */}
        <div className="grid lg:grid-cols-2 gap-20 items-center">
          <LandingHero />
          
          <div className="relative">
            {/* Decorative element behind panel */}
            <div className="absolute inset-0 bg-blue-500/10 blur-[80px] rounded-full scale-90 translate-y-10" />
            <GeneratorPanel />
          </div>
        </div>

        {/* Feature Grid / Social Proof */}
        <div className="mt-32 pt-20 border-t border-slate-900">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-white mb-4">Optimized for the Generative Era</h2>
            <p className="text-slate-400 max-w-2xl mx-auto">
              Emergent Shorts AI follows 2026 standards for AEO, GEO, and high-performance SEO, ensuring your content is found by both humans and AI agents.
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            <FeatureCard 
              title="Answer-First Design" 
              desc="Our content architecture is designed to be easily ingested by AI answer engines like Perplexity and SearchGPT." 
            />
            <FeatureCard 
              title="GEO Enhanced" 
              desc="We use explicit entity linking and declarative sentence structures to boost Generative Engine Optimization." 
            />
            <FeatureCard 
              title="CPU Native" 
              desc="No massive GPU costs. We leverage CPU-optimized Piper and FFmpeg for the most sustainable video generation." 
            />
          </div>
        </div>
      </div>
      
      {/* Footer */}
      <footer className="border-t border-slate-900 py-12 text-center text-slate-500 text-sm">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-6">
          <p>&copy; {new Date().getFullYear()} Emergent Shorts AI. All rights reserved.</p>
          <div className="flex gap-6">
            <span className="hover:text-white cursor-pointer transition-colors">Privacy Policy</span>
            <span className="hover:text-white cursor-pointer transition-colors">Terms of Service</span>
          </div>
        </div>
      </footer>
    </main>
  );
}

function FeatureCard({ title, desc }: { title: string, desc: string }) {
  return (
    <div className="p-8 rounded-3xl bg-slate-900/30 border border-slate-900 hover:border-slate-800 transition-colors">
      <h3 className="text-lg font-bold text-white mb-3">{title}</h3>
      <p className="text-sm text-slate-400 leading-relaxed">{desc}</p>
    </div>
  );
}
